# Generated by Django 5.2.3 on 2025-06-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_excursion_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pickuppoint', verbose_name='Точка сбора'),
        ),
    ]
