# Generated by Django 5.2.3 on 2025-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus_airporttransfer_contactinfo_homepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='airporttransfer',
            options={'verbose_name': 'Трансфер в аэропорт', 'verbose_name_plural': 'Трансферы в аэропорт'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='infomeeting',
            options={'verbose_name': 'Инфо встреча', 'verbose_name_plural': 'Инфо встречи'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_et',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_lt',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_lv',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_et',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_lt',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_lv',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_et',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_lt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_lv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='location_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infomeeting',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='message_uk',
            field=models.TextField(null=True),
        ),
    ]
