# Generated by Django 5.2.3 on 2025-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aboutus_options_alter_airporttransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(upload_to='uploads/homepage/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.TextField(verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_es',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_et',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_lt',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_lv',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_ru',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_uk',
            field=models.TextField(null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
