# Generated by Django 5.2.3 on 2025-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homepage_banner_image_alter_homepage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomeeting',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
