# Generated by Django 5.2.3 on 2025-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_infomeeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airporttransfer',
            name='price',
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_et',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_lt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_lv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airporttransfer',
            name='pickup_location_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
