# Generated by Django 5.2.3 on 2025-06-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_airporttransfer_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('group', 'Групповой'), ('private', 'Индивидуальный')], max_length=10, verbose_name='Тип трансфера')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('departure_time', models.TimeField(verbose_name='Время выезда')),
                ('passenger_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия туриста (если нужно)')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel', verbose_name='Отель')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pickuppoint', verbose_name='Точка сбора')),
            ],
            options={
                'verbose_name': 'Расписание трансфера',
                'verbose_name_plural': 'Расписания трансферов',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
    ]
