# Generated by Django 5.2.3 on 2025-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_region_alter_hotel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('excursions', 'Экскурсии'), ('info_meeting', 'Инфо встреча'), ('airport_transfer', 'Трансфер в аэропорт'), ('ask', 'Задать вопрос'), ('contacts', 'Контакты'), ('about', 'О нас')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='uploads/banners/')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_es', models.CharField(blank=True, max_length=200, null=True)),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True)),
                ('title_et', models.CharField(blank=True, max_length=200, null=True)),
                ('title_lv', models.CharField(blank=True, max_length=200, null=True)),
                ('title_lt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
