# Generated by Django 5.2.3 on 2025-06-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pagebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebanner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры страниц'},
        ),
    ]
