# Generated by Django 5.2.3 on 2025-06-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pagebanner_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='region',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pickup_point', to='core.hotel', verbose_name='Отель (для трансфера)'),
        ),
    ]
