# Generated by Django 5.2.3 on 2025-06-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_hotel_region_hotel_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_transfer', to='core.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hotel', to='core.pickuppoint', verbose_name='Точка сбора'),
        ),
    ]
