# Generated by Django 5.2.3 on 2025-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pickuppoint_hotel_alter_hotel_pickup_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'verbose_name': 'Точки сбора для трансферов', 'verbose_name_plural': 'Точки сбора для трансферов'},
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='transfer_type',
            field=models.CharField(choices=[('group', 'Групповой трансфер'), ('private', 'Индивидуальный трансфер')], default='group', max_length=10, verbose_name='Тип трансфера'),
        ),
    ]
