# Generated by Django 5.2.3 on 2025-06-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_pickuppoint_options_pickuppoint_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='core.hotel', verbose_name='Отель'),
        ),
    ]
