# Generated by Django 5.2.3 on 2025-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_grouptransferpickuppoint_privatetransferpickuppoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferschedule',
            options={'ordering': ['departure_date', 'departure_time'], 'verbose_name': 'Расписание трансфера', 'verbose_name_plural': 'Массовое добавление расписания трансферов'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
    ]
