# Generated by Django 5.2.3 on 2025-06-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_transferschedule_options_hotel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='core.region'),
        ),
    ]
