# Generated by Django 5.2.3 on 2025-06-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_hotel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата трансфера')),
                ('transfer_type', models.CharField(choices=[('group', 'Групповой'), ('private', 'Индивидуальный')], max_length=10, verbose_name='Тип трансфера')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel',
        ),
        migrations.AddField(
            model_name='transferschedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.transferschedulegroup', verbose_name='Группа трансфера'),
        ),
    ]
