# Generated by Django 5.2.3 on 2025-06-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transferschedulegroup_remove_hotel_hotel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.CreateModel(
            name='TransferNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('transfer_type', models.CharField(choices=[('group', 'Group Transfer'), ('private', 'Private Transfer')], max_length=10, verbose_name='Transfer Type')),
                ('transfer_date', models.DateField(verbose_name='Transfer Date')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('et', 'Eesti'), ('uk', 'Українська'), ('es', 'Español')], default='ru', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Transfer Notification',
                'verbose_name_plural': 'Transfer Notifications',
                'unique_together': {('email', 'hotel', 'transfer_type', 'transfer_date')},
            },
        ),
    ]
