# Generated by Django 5.2.3 on 2025-06-24 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_hotel_options_transfernotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfernotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transfernotification',
            name='departure_date',
            field=models.DateField(default=datetime.date(2025, 6, 30), verbose_name='Departure Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfernotification',
            name='transfer_type',
            field=models.CharField(choices=[('group', 'Group'), ('private', 'Private')], max_length=10, verbose_name='Transfer Type'),
        ),
        migrations.RemoveField(
            model_name='transfernotification',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='transfernotification',
            name='transfer_date',
        ),
    ]
