# Generated by Django 5.2.3 on 2025-06-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_transfernotification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel')),
            ],
        ),
    ]
