# Generated by Django 5.2.3 on 2025-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transferinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinquiry',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferinquiry',
            name='reply',
            field=models.TextField(blank=True, verbose_name='Ответ админа'),
        ),
    ]
