# Generated by Django 5.2.3 on 2025-06-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_transferinquiry_replied_transferinquiry_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferInquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reply_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.transferinquiry')),
            ],
        ),
    ]
