# Generated by Django 5.2.3 on 2025-06-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transferinquirylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfernotification',
            name='departure_time_sent',
            field=models.TimeField(blank=True, null=True, verbose_name='Sent Departure Time'),
        ),
        migrations.CreateModel(
            name='TransferScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('pickup_point', models.CharField(blank=True, max_length=255)),
                ('tourist_last_name', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transferschedulegroup')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
