# Generated by Django 5.2.3 on 2025-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_transferchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfernotification',
            name='passenger_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
