# Generated by Django 5.2.3 on 2025-06-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_transfernotification_passenger_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfernotification',
            name='passenger_last_name',
        ),
    ]
