# Generated by Django 5.2.3 on 2025-07-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_transfernotification_passenger_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfernotification',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('excursions', 'Экскурсии'), ('info_meeting', 'Инфо встреча'), ('airport_transfer', 'Трансфер в аэропорт'), ('ask', 'Задать вопрос'), ('contacts', 'Контакты'), ('about', 'О нас'), ('group_transfer', 'Групповой трансфер')], max_length=50, unique=True),
        ),
    ]
