# Generated by Django 5.2.3 on 2025-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_transfernotification_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinquiry',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
