# Generated by Django 5.2.3 on 2025-07-13 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст политики'),
        ),
    ]
