# Generated by Django 5.2.3 on 2025-07-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMeetingScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.infomeeting')),
            ],
            options={
                'verbose_name': 'Расписание инфо встречи',
                'verbose_name_plural': 'Расписания инфо встреч',
                'ordering': ['date', 'time_from'],
            },
        ),
    ]
