# Generated by Django 5.2.3 on 2025-07-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_infomeetingscheduleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomeetingscheduleitem',
            name='meeting',
        ),
    ]
