# Generated by Django 5.2.3 on 2025-07-13 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_infomeetingscheduleitem_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomeeting',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_et',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_lt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_lv',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infomeeting',
            name='content_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
