# Generated by Django 5.2.3 on 2025-07-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_infomeeting_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infomeetingscheduleitem',
            options={'ordering': ['date', 'time_from', 'time_to', 'hotel'], 'verbose_name': 'Расписание инфо встречи', 'verbose_name_plural': 'Расписания инфо встреч'},
        ),
        migrations.CreateModel(
            name='ExcursionPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('MALAGA_TO_GIB', 'От Малаги к Гибралтару'), ('GIB_TO_MALAGA', 'От Гибралтара к Малаге')], max_length=20, verbose_name='Направление экскурсии')),
                ('pickup_point_name', models.CharField(max_length=200, verbose_name='Название точки сбора')),
                ('pickup_time', models.TimeField(verbose_name='Время отправления')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена взрослый')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена ребёнок')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excursion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
            options={
                'verbose_name': 'Точка сбора экскурсии',
                'verbose_name_plural': 'Точки сбора экскурсий',
                'unique_together': {('excursion', 'hotel')},
            },
        ),
    ]
