# Generated by Django 5.2.3 on 2025-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_infomeetingscheduleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
