# Generated by Django 5.2.3 on 2025-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_excursionpickuppoint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=36.6, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-4.5, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
