# Generated by Django 5.2.3 on 2025-07-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_excursionpickuppoint_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionRegionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена взрослый')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена ребёнок')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='core.excursion', verbose_name='Экскурсия')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Цена экскурсии по региону',
                'verbose_name_plural': 'Цены экскурсий по регионам',
                'unique_together': {('excursion', 'region')},
            },
        ),
    ]
