# Generated by Django 5.2.3 on 2025-07-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_excursionregionprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='price_adult',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='price_child',
        ),
    ]
