# Generated by Django 5.2.3 on 2025-07-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_excursionpickuppoint_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='pickup_point_name',
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='custom_pickup_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название новой точки сбора'),
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='direction',
            field=models.CharField(choices=[('MALAGA_TO_GIB', 'От Малаги к Гибралтару'), ('GIB_TO_MALAGA', 'От Гибралтара к Малаге')], default='GIB_TO_MALAGA', max_length=20, verbose_name='Направление экскурсии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_pickups', to='core.pickuppoint', verbose_name='Точка сбора (из списка)'),
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена взрослый'),
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='price_child',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена ребёнок'),
        ),
    ]
