# Generated by Django 5.2.3 on 2025-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_excursionpickuppoint_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='custom_pickup_name',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='price_adult',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='price_child',
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='pickup_point_name',
            field=models.CharField(default=0.0, max_length=200, verbose_name='Название точки сбора'),
            preserve_default=False,
        ),
    ]
