# Generated by Django 5.2.3 on 2025-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_excursion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursioncontentblock',
            name='block_type',
            field=models.CharField(choices=[('description', 'Описание'), ('rules', 'Правила проведения'), ('what_to_bring', 'Что иметь при себе'), ('custom', 'Дополнительно')], default='custom', max_length=50, verbose_name='Тип блока'),
        ),
    ]
