# Generated by Django 5.2.3 on 2025-08-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_excursioncontentblock_content_en_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excursionpickuppoint',
            unique_together={('excursion', 'hotel', 'direction')},
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='direction',
            field=models.CharField(choices=[('malaga', 'В сторону Малаги'), ('gibraltar', 'В сторону Гибралтара')], default='malaga', max_length=20, verbose_name='Направление'),
        ),
        migrations.CreateModel(
            name='HotelDirectionPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('malaga', 'В сторону Малаги'), ('gibraltar', 'В сторону Гибралтара')], max_length=20, verbose_name='Направление')),
                ('pickup_point_name', models.CharField(max_length=200, verbose_name='Название точки сбора')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_pickups', to='core.hotel')),
            ],
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='longitude',
        ),
    ]
