# Generated by Django 5.2.3 on 2025-08-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_excursionpickuppoint_unique_together_and_more'),
        ('core', '0051_add_direction_to_excursion'),
    ]

    operations = [
    ]
