# Generated by Django 5.2.3 on 2025-08-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_create_hoteldirectionpickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldirectionpickup',
            name='pickup_point_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hoteldirectionpickup',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldirectionpickup',
            name='direction',
            field=models.CharField(choices=[('malaga', 'В сторону Малаги'), ('gibraltar', 'В сторону Гибралтара')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hoteldirectionpickup',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_pickups', to='core.hotel'),
        ),
        migrations.AlterField(
            model_name='hoteldirectionpickup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hoteldirectionpickup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldirectionpickup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hoteldirectionpickup',
            unique_together={('hotel', 'direction')},
        ),
    ]
