# Generated by Django 5.2.3 on 2025-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_hoteldirectionpickup_pickup_point_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excursionpickuppoint',
            unique_together={('excursion', 'hotel')},
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.DeleteModel(
            name='HotelDirectionPickup',
        ),
        migrations.RemoveField(
            model_name='excursionpickuppoint',
            name='direction',
        ),
    ]
