# Generated by Django 5.2.3 on 2025-08-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_excursionpickuppoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_pickups', to='core.pickuppoint', verbose_name='Точка сбора'),
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='pickup_point_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название точки сбора'),
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отправления'),
        ),
    ]
