# Generated by Django 5.2.3 on 2025-08-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_excursionpickuppoint_pickup_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionPickupReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название точки сбора')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('default_time', models.TimeField(blank=True, null=True, verbose_name='Время по умолчанию')),
            ],
            options={
                'verbose_name': 'Справочник точек сбора',
                'verbose_name_plural': 'Справочник точек сбора',
            },
        ),
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='pickup_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_pickups', to='core.excursionpickupreference', verbose_name='Ссылка на готовую точку'),
        ),
    ]
