# Generated by Django 5.2.3 on 2025-08-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_excursionpickupreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionpickuppoint',
            name='copy_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='core.excursionpickuppoint', verbose_name='Использовать готовую точку'),
        ),
    ]
