# Generated by Django 5.2.3 on 2025-08-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_excursionpickuppoint_copy_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='excursions/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.excursion')),
            ],
        ),
    ]
