# Generated by Django 5.2.3 on 2025-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_excursionimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='message',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_et',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_lt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_lv',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_uk',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('transfer', 'Вопрос по трансферу'), ('excursion', 'Вопрос по экскурсии'), ('organization', 'Организационный вопрос'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='hotel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_es',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_et',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_lt',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_lv',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
