# Generated by Django 5.2.3 on 2025-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_question_options_remove_question_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('et', 'Eesti'), ('uk', 'Українська')], default='ru', max_length=5, verbose_name='Язык'),
        ),
    ]
