# Generated by Django 5.2.3 on 2025-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('ask', 'Страница «Задать вопрос»'), ('contacts', 'Страница «Контакты»')], default='ask', max_length=20, verbose_name='Источник'),
        ),
    ]
