# Generated by Django 5.2.3 on 2025-08-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_question_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='No message', verbose_name='Текст вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_et',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_lt',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_lv',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_uk',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
    ]
