# Generated by Django 5.2.3 on 2025-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('transfer_home', 'Трансферы (общая страница)'), ('transfer_group', 'Групповой трансфер'), ('transfer_private', 'Индивидуальный трансфер')], db_index=True, max_length=32)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [ru]')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [en]')),
                ('title_es', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [es]')),
                ('title_lt', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [lt]')),
                ('title_lv', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [lv]')),
                ('title_et', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [et]')),
                ('title_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок [uk]')),
                ('content_ru', models.TextField(blank=True, default='', verbose_name='Содержание [ru]')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='Содержание [en]')),
                ('content_es', models.TextField(blank=True, default='', verbose_name='Содержание [es]')),
                ('content_lt', models.TextField(blank=True, default='', verbose_name='Содержание [lt]')),
                ('content_lv', models.TextField(blank=True, default='', verbose_name='Содержание [lv]')),
                ('content_et', models.TextField(blank=True, default='', verbose_name='Содержание [et]')),
                ('content_uk', models.TextField(blank=True, default='', verbose_name='Содержание [uk]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блок контента (трансферы)',
                'verbose_name_plural': 'Блоки контента (трансферы)',
                'ordering': ('page', 'order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('excursions', 'Экскурсии'), ('info_meeting', 'Инфо встреча'), ('airport_transfer', 'Трансфер в аэропорт'), ('ask', 'Задать вопрос'), ('contacts', 'Контакты'), ('about', 'О нас'), ('group_transfer', 'Групповой трансфер'), ('private_transfer', 'Индивидуальный трансфер')], max_length=50, unique=True),
        ),
    ]
