# Generated by Django 5.2.3 on 2025-08-19 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_transferpagecontentblock_alter_pagebanner_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_es',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_et',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_lt',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_lv',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_uk',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Подзаголовок'),
        ),
    ]
