# Generated by Django 5.2.3 on 2025-08-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_homepage_subtitle_alter_homepage_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferschedule',
            name='booking_service_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер услуги/заявки'),
        ),
        migrations.AlterField(
            model_name='transferschedule',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.CreateModel(
            name='TransferPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='core.transferschedule')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('schedule', 'last_name', 'first_name')},
            },
        ),
    ]
