# Generated by Django 5.2.3 on 2025-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_transferschedule_booking_service_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferpassenger',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='transferpassenger',
            constraint=models.UniqueConstraint(condition=models.Q(('first_name', ''), _negated=True), fields=('schedule', 'last_name', 'first_name'), name='uniq_passenger_when_first_name_present'),
        ),
    ]
