# Generated by Django 5.2.3 on 2025-08-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_transferpassenger_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_pickups', to='core.hotel', verbose_name='Отель'),
        ),
        migrations.CreateModel(
            name='HotelExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна из отеля')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_flags', to='core.excursion', verbose_name='Экскурсия')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_flags', to='core.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Доступность экскурсии из отеля',
                'verbose_name_plural': 'Доступность экскурсий из отеля',
                'unique_together': {('hotel', 'excursion')},
            },
        ),
    ]
