# Generated by Django 5.2.3 on 2025-08-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_transferpassenger_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionpickupreference',
            name='direction',
            field=models.CharField(choices=[('MALAGA_TO_GIB', 'От Малаги к Гибралтару'), ('GIB_TO_MALAGA', 'От Гибралтара к Малаге')], default='MALAGA_TO_GIB', max_length=16, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='excursionpickupreference',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Локация (Malaga, Torremolinos Centro и т.п.)'),
        ),
        migrations.AlterUniqueTogether(
            name='excursionpickupreference',
            unique_together={('name', 'direction', 'locality')},
        ),
        migrations.CreateModel(
            name='ExcursionZoneTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=64, verbose_name='Зона/Локация')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время сбора')),
                ('direction', models.CharField(choices=[('MALAGA_TO_GIB', 'От Малаги к Гибралтару'), ('GIB_TO_MALAGA', 'От Гибралтара к Малаге')], default='MALAGA_TO_GIB', max_length=16, verbose_name='Направление')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_times', to='core.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Базовое время по зоне',
                'verbose_name_plural': 'Базовые времена по зонам',
                'unique_together': {('excursion', 'zone', 'direction')},
            },
        ),
    ]
