# Generated by Django 5.2.3 on 2025-08-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_excursionpickuppoint_hotel_hotelexcursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Временная зона (экскурсии)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Временная зона (экскурсии)',
                'verbose_name_plural': 'Временные зоны (экскурсии)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='excursion_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='core.excursionzone', verbose_name='Временная зона (экскурсии)'),
        ),
    ]
