# Generated by Django 5.2.3 on 2025-08-31 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_excursionzone_hotel_excursion_zone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excursionpickuppoint',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='core.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AlterField(
            model_name='excursionpickuppoint',
            name='pickup_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_pickups', to='core.excursionpickupreference', verbose_name='Справочник точки'),
        ),
        migrations.AddIndex(
            model_name='excursionpickuppoint',
            index=models.Index(fields=['excursion', 'pickup_point_name'], name='idx_excursion_pickupname'),
        ),
        migrations.AddConstraint(
            model_name='excursionpickuppoint',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('excursion', 'hotel'), name='uniq_excursion_hotel'),
        ),
    ]
