# Generated by Django 5.2.3 on 2025-09-06 11:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_excursionpickuppoint_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('et', 'Eesti'), ('ru', 'Русский'), ('uk', 'Українська')], max_length=5, unique=True, verbose_name='Language code')),
                ('title', models.CharField(default='Правила поведения на экскурсиях', max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content (HTML)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excursion rules',
                'verbose_name_plural': 'Excursion rules',
                'ordering': ['language_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='excursionpickuppoint',
            options={'ordering': ['pickup_time', 'hotel__name', 'pickup_point_name'], 'verbose_name': 'Точка сбора экскурсии', 'verbose_name_plural': 'Точки сбора экскурсий'},
        ),
        migrations.AlterUniqueTogether(
            name='excursionpickuppoint',
            unique_together={('excursion', 'hotel')},
        ),
    ]
