# Generated by Django 5.2.3 on 2025-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_excursionrules_alter_excursionpickuppoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_es', models.CharField(blank=True, default='', max_length=255)),
                ('title_uk', models.CharField(blank=True, default='', max_length=255)),
                ('title_lt', models.CharField(blank=True, default='', max_length=255)),
                ('title_lv', models.CharField(blank=True, default='', max_length=255)),
                ('title_et', models.CharField(blank=True, default='', max_length=255)),
                ('content_ru', models.TextField(blank=True, default='')),
                ('content_en', models.TextField(blank=True, default='')),
                ('content_es', models.TextField(blank=True, default='')),
                ('content_uk', models.TextField(blank=True, default='')),
                ('content_lt', models.TextField(blank=True, default='')),
                ('content_lv', models.TextField(blank=True, default='')),
                ('content_et', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контент страницы «Задать вопрос»',
                'verbose_name_plural': 'Контент страницы «Задать вопрос»',
            },
        ),
    ]
