# Generated by Django 5.2.3 on 2025-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_askpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык экскурсии',
                'verbose_name_plural': 'Языки экскурсии',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='guide_languages',
            field=models.ManyToManyField(blank=True, help_text='Выберите языки, на которых проводится экскурсия', related_name='excursions', to='core.language', verbose_name='Доступные языки экскурсии (язык гида)'),
        ),
    ]
