# Generated by Django 5.2.3 on 2025-09-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_language_excursion_guide_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='guide_languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
