# Generated by Django 5.2.3 on 2025-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_excursion_guide_languages_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='lang_de',
            field=models.BooleanField(default=False, verbose_name='Немецкий'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='lang_en',
            field=models.BooleanField(default=False, verbose_name='Английский'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='lang_es',
            field=models.BooleanField(default=False, verbose_name='Испанский'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='lang_fr',
            field=models.BooleanField(default=False, verbose_name='Французский'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='lang_ru',
            field=models.BooleanField(default=False, verbose_name='Русский'),
        ),
    ]
