# Generated by Django 5.2.3 on 2025-09-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_excursion_lang_de_excursion_lang_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, default='', verbose_name='Detail (RU)')),
                ('text_en', models.TextField(blank=True, default='', verbose_name='Detail (EN)')),
                ('text_es', models.TextField(blank=True, default='', verbose_name='Detail (ES)')),
                ('text_lt', models.TextField(blank=True, default='', verbose_name='Detail (LT)')),
                ('text_lv', models.TextField(blank=True, default='', verbose_name='Detail (LV)')),
                ('text_et', models.TextField(blank=True, default='', verbose_name='Detail (ET)')),
                ('text_uk', models.TextField(blank=True, default='', verbose_name='Detail (UK)')),
                ('included_tickets', models.TextField(blank=True, default='', verbose_name='Included tickets (any language)')),
                ('not_included', models.TextField(blank=True, default='', verbose_name='Not included (any language)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excursion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.excursion', verbose_name='Excursion')),
            ],
            options={
                'verbose_name': 'Подробное описание экскурсий',
                'verbose_name_plural': 'Подробное описание экскурсий',
            },
        ),
    ]
