# Generated by Django 5.2.3 on 2025-09-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_excursiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionLongDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, default='', verbose_name='Long description (RU)')),
                ('text_en', models.TextField(blank=True, default='', verbose_name='Long description (EN)')),
                ('text_es', models.TextField(blank=True, default='', verbose_name='Long description (ES)')),
                ('text_lt', models.TextField(blank=True, default='', verbose_name='Long description (LT)')),
                ('text_lv', models.TextField(blank=True, default='', verbose_name='Long description (LV)')),
                ('text_et', models.TextField(blank=True, default='', verbose_name='Long description (ET)')),
                ('text_uk', models.TextField(blank=True, default='', verbose_name='Long description (UK)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excursion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_detail', to='core.excursion', verbose_name='Excursion')),
            ],
            options={
                'verbose_name': 'Excursion long detail',
                'verbose_name_plural': 'Excursion long details',
            },
        ),
        migrations.DeleteModel(
            name='ExcursionDetail',
        ),
    ]
